title: Project
pages: false
files:
  sortable: true
fields:
  title:
    label: Title
    type:  text
  mainTitleLine1:
    label: Main Title
    type: text
  mainTitleLine2:
    label: Main Title
    type: text
  coverImage:
    label: Cover Image
    type: image
  directUrl:
    label: Live Project url
    type:  url
  type: 
    label: Project type
    type:  text
    width: 1/2
  period: 
    label: Project period
    type:  text
    width: 1/2
  role: 
    label: Project role
    type:  text
    width: 1/2
  technos:
    label: Project technos
    type:  text
    width: 1/2
  line: 
    type: line
  projectLandingTitle:
    label: projectLandingTitle
    type: text
    width: 1/4
  projectLandingSubTitle:
    label: projectLandingSubTitle
    type: text
    width: 1/4
  projectLandingText:
    label: projectLandingText
    type: textarea
    width: 1/2
  projectType:
    label: projectType
    type: text
    width: 1/4
  projectPeriod:
    label: projectPeriod
    type: text
    width: 1/4
  projectClient:
    label: projectClient
    type: text
    width: 1/4
  projectRole:
    label: projectRole
    type: text
    width: 1/4
